apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.nginx.service.name }}
spec:
  selector:
    app: {{ .Values.nginx.label }}
  type: {{ .Values.nginx.service.type }}
  ports:
   - port: {{ .Values.nginx.service.port }}
     targetPort: {{ .Values.nginx.service.targetport}}
     nodePort: {{ .Values.nginx.service.nodeport }}
